<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DoctorsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('doctors')->insert([
            [
                'user_id' => 1,
                'specialty' => 'General Practitioner',
                'license_number' => 'DRL-001-2020',
                'experience_years' => 5,
                'bio' => 'Experienced general practitioner with focus on preventive healthcare services.',
                'phone' => '08123456789',
                'email' => 'doctor1@vitaguard.com',
                'address' => 'Jl. Kesehatan No. 123, Jakarta Pusat',
                'rating' => 4.8,
                'status' => 'active',
                'date_of_birth' => '1985-03-15',
                'gender' => 'Laki-laki',
                'photo' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'specialty' => 'Pediatrician',
                'license_number' => 'DRL-002-2019',
                'experience_years' => 8,
                'bio' => 'Pediatric specialist with experience at leading hospitals.',
                'phone' => '08129876543',
                'email' => 'doctor2@vitaguard.com',
                'address' => 'Jl. Medika No. 456, Jakarta Selatan',
                'rating' => 5.0,
                'status' => 'active',
                'date_of_birth' => '1982-07-22',
                'gender' => 'Perempuan',
                'photo' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'specialty' => 'Internal Medicine',
                'license_number' => 'DRL-003-2018',
                'experience_years' => 10,
                'bio' => 'Internal medicine doctor with focus on chronic disease management.',
                'phone' => '081311223344',
                'email' => 'doctor3@vitaguard.com',
                'address' => 'Jl. Sehat Selalu No. 12, Bandung',
                'rating' => 4.7,
                'status' => 'active',
                'date_of_birth' => '1980-11-08',
                'gender' => 'Laki-laki',
                'photo' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'specialty' => 'Clinical Psychologist',
                'license_number' => 'DRL-004-2021',
                'experience_years' => 6,
                'bio' => 'Clinical psychologist specializing in work stress and anxiety disorders.',
                'phone' => '081355667788',
                'email' => 'doctor4@vitaguard.com',
                'address' => 'Jl. Harmoni No. 8, Yogyakarta',
                'rating' => 4.9,
                'status' => 'active',
                'date_of_birth' => '1988-05-30',
                'gender' => 'Perempuan',
                'photo' => 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'specialty' => 'Clinical Nutritionist',
                'license_number' => 'DRL-005-2022',
                'experience_years' => 4,
                'bio' => 'Experienced in developing personalized nutrition programs.',
                'phone' => '081377889900',
                'email' => 'doctor5@vitaguard.com',
                'address' => 'Jl. Cemerlang No. 21, Surabaya',
                'rating' => 4.6,
                'status' => 'active',
                'date_of_birth' => '1990-09-12',
                'gender' => 'Laki-laki',
                'photo' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'specialty' => 'Dermatologist',
                'license_number' => 'DRL-006-2019',
                'experience_years' => 7,
                'bio' => 'Dermatology specialist with expertise in skin care and treatment.',
                'phone' => '081399112233',
                'email' => 'doctor6@vitaguard.com',
                'address' => 'Jl. Kulit Sehat No. 34, Medan',
                'rating' => 4.8,
                'status' => 'active',
                'date_of_birth' => '1984-01-25',
                'gender' => 'Perempuan',
                'photo' => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'specialty' => 'Cardiologist',
                'license_number' => 'DRL-007-2017',
                'experience_years' => 12,
                'bio' => 'Experienced cardiologist specializing in heart disease management.',
                'phone' => '081344556677',
                'email' => 'doctor7@vitaguard.com',
                'address' => 'Jl. Jantung Sehat No. 56, Semarang',
                'rating' => 4.9,
                'status' => 'active',
                'date_of_birth' => '1978-06-14',
                'gender' => 'Laki-laki',
                'photo' => 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'specialty' => 'Orthopedist',
                'license_number' => 'DRL-008-2018',
                'experience_years' => 9,
                'bio' => 'Orthopedic specialist with expertise in bone and joint treatment.',
                'phone' => '081388999000',
                'email' => 'doctor8@vitaguard.com',
                'address' => 'Jl. Tulang Kuat No. 78, Makassar',
                'rating' => 4.7,
                'status' => 'active',
                'date_of_birth' => '1986-10-02',
                'gender' => 'Laki-laki',
                'photo' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 9,
                'specialty' => 'ENT Specialist',
                'license_number' => 'DRL-009-2020',
                'experience_years' => 5,
                'bio' => 'Ear, nose and throat specialist with focus on respiratory health.',
                'phone' => '081311223344',
                'email' => 'doctor9@vitaguard.com',
                'address' => 'Jl. THT No. 12, Palembang',
                'rating' => 4.6,
                'status' => 'active',
                'date_of_birth' => '1987-04-19',
                'gender' => 'Perempuan',
                'photo' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 10,
                'specialty' => 'Ophthalmologist',
                'license_number' => 'DRL-010-2021',
                'experience_years' => 6,
                'bio' => 'Eye specialist with expertise in vision care and eye surgery.',
                'phone' => '081366778899',
                'email' => 'doctor10@vitaguard.com',
                'address' => 'Jl. Mata Sehat No. 90, Bandung',
                'rating' => 4.8,
                'status' => 'active',
                'date_of_birth' => '1989-08-07',
                'gender' => 'Perempuan',
                'photo' => 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500&h=500&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
