<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MembersSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('members')->insert([
            [
                'user_id' => 11,
                'date_of_birth' => '1990-05-15',
                'gender' => 'Laki-laki',
                'phone' => '08123456789',
                'address' => 'Jl. Kesehatan No. 123, Jakarta Pusat',
                'blood_type' => 'O+',
                'weight' => 70,
                'height' => 175,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 12,
                'date_of_birth' => '1988-08-22',
                'gender' => 'Perempuan',
                'phone' => '08129876543',
                'address' => 'Jl. Medika No. 456, Jakarta Selatan',
                'blood_type' => 'A-',
                'weight' => 60,
                'height' => 165,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 13,
                'date_of_birth' => '1995-12-03',
                'gender' => 'Laki-laki',
                'phone' => '081311223344',
                'address' => 'Jl. Sehat Selalu No. 12, Bandung',
                'blood_type' => 'B+',
                'weight' => 75,
                'height' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 14,
                'date_of_birth' => '1992-02-14',
                'gender' => 'Perempuan',
                'phone' => '081355667788',
                'address' => 'Jl. Harmoni No. 8, Yogyakarta',
                'blood_type' => 'AB+',
                'weight' => 58,
                'height' => 162,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 15,
                'date_of_birth' => '1998-07-09',
                'gender' => 'Laki-laki',
                'phone' => '081377889900',
                'address' => 'Jl. Cemerlang No. 21, Surabaya',
                'blood_type' => 'O-',
                'weight' => 72,
                'height' => 178,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 16,
                'date_of_birth' => '1991-03-18',
                'gender' => 'Perempuan',
                'phone' => '081399112233',
                'address' => 'Jl. Kulit Sehat No. 34, Medan',
                'blood_type' => 'A+',
                'weight' => 62,
                'height' => 168,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 17,
                'date_of_birth' => '1987-11-26',
                'gender' => 'Laki-laki',
                'phone' => '081344556677',
                'address' => 'Jl. Jantung Sehat No. 56, Semarang',
                'blood_type' => 'B-',
                'weight' => 78,
                'height' => 182,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 18,
                'date_of_birth' => '1994-09-05',
                'gender' => 'Perempuan',
                'phone' => '081388999000',
                'address' => 'Jl. Tulang Kuat No. 78, Makassar',
                'blood_type' => 'AB-',
                'weight' => 64,
                'height' => 170,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 19,
                'date_of_birth' => '1993-06-20',
                'gender' => 'Laki-laki',
                'phone' => '081311223344',
                'address' => 'Jl. THT No. 12, Palembang',
                'blood_type' => 'O+',
                'weight' => 74,
                'height' => 179,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 20,
                'date_of_birth' => '1996-01-12',
                'gender' => 'Perempuan',
                'phone' => '081366778899',
                'address' => 'Jl. Mata Sehat No. 90, Bandung',
                'blood_type' => 'A+',
                'weight' => 61,
                'height' => 166,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
