<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TransactionsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('transactions')->insert([
            [
                'transaction_code' => 'TRX-' . date('YmdHis') . '-' . Str::random(4),
                'member_id' => 1,
                'service_id' => 1,
                'doctor_id' => 1,
                'consultation_date' => now()->addDay(),
                'patient_complaints' => 'Demam ringan dan sakit kepala',
                'doctor_diagnosis' => 'Flu biasa, istirahat dan minum air yang cukup',
                'status' => 'completed',
                'payment_status' => 'paid',
                'amount' => 50000,
                'payment_method' => 'transfer',
                'notes' => 'Konsultasi untuk keluhan demam ringan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'transaction_code' => 'TRX-' . date('YmdHis') . '-' . Str::random(4),
                'member_id' => 2,
                'service_id' => 1,
                'doctor_id' => 2,
                'consultation_date' => now()->addDays(2),
                'patient_complaints' => 'Pemeriksaan kesehatan rutin',
                'doctor_diagnosis' => 'Kondisi kesehatan baik, lanjutkan pola hidup sehat',
                'status' => 'pending',
                'payment_status' => 'unpaid',
                'amount' => 50000,
                'payment_method' => 'e-wallet',
                'notes' => 'Konsultasi untuk pemeriksaan kesehatan rutin.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'transaction_code' => 'TRX-' . date('YmdHis') . '-' . Str::random(4),
                'member_id' => 3,
                'service_id' => 3,
                'doctor_id' => 2,
                'consultation_date' => now()->addDays(3),
                'patient_complaints' => 'Anak sulit makan dan berat badan tidak naik',
                'doctor_diagnosis' => 'Perlu evaluasi nutrisi dan jadwal makan teratur',
                'status' => 'completed',
                'payment_status' => 'paid',
                'amount' => 150000,
                'payment_method' => 'virtual account',
                'notes' => 'Konsultasi spesialis anak terkait tumbuh kembang.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'transaction_code' => 'TRX-' . date('YmdHis') . '-' . Str::random(4),
                'member_id' => 4,
                'service_id' => 4,
                'doctor_id' => 3,
                'consultation_date' => now()->addDays(1),
                'patient_complaints' => 'Ingin pemeriksaan darah untuk medical checkup',
                'doctor_diagnosis' => 'Direkomendasikan cek darah lengkap dan kontrol lanjutan',
                'status' => 'completed',
                'payment_status' => 'paid',
                'amount' => 200000,
                'payment_method' => 'transfer',
                'notes' => 'Pemeriksaan rutin tahunan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'transaction_code' => 'TRX-' . date('YmdHis') . '-' . Str::random(4),
                'member_id' => 5,
                'service_id' => 5,
                'doctor_id' => 4,
                'consultation_date' => now()->addDays(4),
                'patient_complaints' => 'Sering cemas dan sulit tidur',
                'doctor_diagnosis' => 'Kecemasan ringan, disarankan terapi lanjutan dan sleep hygiene',
                'status' => 'pending',
                'payment_status' => 'unpaid',
                'amount' => 175000,
                'payment_method' => 'e-wallet',
                'notes' => 'Sesi konseling pertama.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'transaction_code' => 'TRX-' . date('YmdHis') . '-' . Str::random(4),
                'member_id' => 6,
                'service_id' => 6,
                'doctor_id' => 5,
                'consultation_date' => now()->addDays(5),
                'patient_complaints' => 'Ingin menurunkan berat badan secara sehat',
                'doctor_diagnosis' => 'Program diet bertahap dengan defisit kalori terkontrol',
                'status' => 'completed',
                'payment_status' => 'paid',
                'amount' => 120000,
                'payment_method' => 'credit card',
                'notes' => 'Follow-up dijadwalkan 2 minggu lagi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'transaction_code' => 'TRX-' . date('YmdHis') . '-' . Str::random(4),
                'member_id' => 7,
                'service_id' => 7,
                'doctor_id' => 3,
                'consultation_date' => now()->addDays(6),
                'patient_complaints' => 'Kontrol tekanan darah untuk orang tua',
                'doctor_diagnosis' => 'Tekanan darah stabil, lanjutkan obat dan olahraga ringan',
                'status' => 'completed',
                'payment_status' => 'paid',
                'amount' => 160000,
                'payment_method' => 'transfer',
                'notes' => 'Pasien lansia dengan riwayat hipertensi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
